name: Checkmarx One Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - master
      - develop
  push:
    branches:
      - main
      - master
      - develop
jobs:
  scan:                   # <— job id
    name: scan            # <— user-facing job name = shows in Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkmarx One CLI Action
        uses: Checkmarx/ast-github-action@v2
        with:
          project_name: rudy-marquez/vulnado
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: https://deu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: "--scan-types sast,sca"
          
